#title in header
title: "Littlelamb's Blog"

#main info
#owner
owner: "I am HanlinXu"
email: hanlinxu2002@gmail.com
info: "A student major in Biomedical Science at Shanghai Jiao Tong Unversity"
#description
desc: "Keep thinking and keep learning"

#menu
menu:
  Works: /Works
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
github: https://github.com/thelittlelamb
Zhihu: https://www.zhihu.com/people/xiao-xu-xiao-xu-qi-bu-lai-chuang-32

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/cat.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

